### ISSUE TITLE
Script errors out when trying to process a System Manager based network

### ISSUE THREAD

**Issue by phdonnelly** [picnicsecurity/Meraki-Traffic-Analyzer#3]
Sorry, somehow submitted the previous incomplete issue as I was typing it.

I was giving this a shot and the script crashes when it tries to process our MDM/System Manager network; presumably because it doesn't have many/most of the same attributes the regular MX/MS/MR based networks do.

Scrubbed CLI output below:

```
-------------------------------------------------------------------------------------------------------------------------
VERBOSE: Gathering identifiers
VERBOSE: Gathering VPN data
=========================================================================================================================
Processing XYZ Mobile Devices:  20%|█████████▍                                     | 20/100 [00:00<00:00, 27253.44it/s]Traceback (most recent call last):
  File "MTA.py", line 1568, in <module>
    sites = get_sites(dashboard, orgID, networks, get_clients=True)
  File "MTA.py", line 910, in get_sites
    peers = get_org_remote_vpn_participants(dashboard, organizationId, networkId)
  File "MTA.py", line 144, in get_org_remote_vpn_participants
    siteVpnData = siteVpnData[0]
IndexError: list index out of range
Processing XYZ Mobile Devices:  20%|██████████                                        | 20/100 [00:02<00:10,  7.80it/s]
```

**Comment by JustOneMoreDog** [comment]
An MDM network is not something I have worked with yet so let's try some things out and see if we can get this figured out. It would appear something wonky is going on in the get_org_remote_vpn_participants function. Can you change the function to the following and let me know what the output is please? 

```
def get_org_remote_vpn_participants(dashboard, organizationId, networkId):
    # This shows us what each site is connected to on the S2S VPN
    orgVpnData = dashboard.appliance.getOrganizationApplianceVpnStats(organizationId=organizationId)
    siteVpnData = None
    siteVpnData = [network for network in orgVpnData if network['networkId'] == networkId]
	print("Debug:")
	print(len(siteVpnData))
	print(siteVpnData)
	print(orgVpnData)
    if siteVpnData is not None:
        siteVpnData = siteVpnData[0]
	peers = [(peer['networkId'], peer['networkName']) for peer in siteVpnData['merakiVpnPeers']]
	peers.append((siteVpnData['networkId'], siteVpnData['networkName']))
	print("Returning peers")
	return peers
    else:
	print("Returning None")
	return None
```

Feel free to scrub any data in the dictionary/lists that get printed. Mainly just need to know what type of data is popping out here.

Thanks!

**Comment by phdonnelly** [comment]
Got it; debug outputs from the run are:
len(siteVpnData) = 0
siteVpnData = []
orgVpnData = a gigantic list of JSON objects too big to paste here

and then script errored out with the same list index out of range exception

Since it looked like the problem may be that siteVpnData is an empty list instead of just being an empty object, I changed your test against siteVpnData to:

```
 if siteVpnData is not None and len(siteVpnData) > 0:
```

and re-ran it once more; got further along, but then errored out again:

```
Traceback (most recent call last):
  File "MTA.py", line 1585, in <module>
    sites = get_sites(dashboard, orgID, networks, get_clients=True)
  File "MTA.py", line 931, in get_sites
    for subnet in dashboard.appliance.getNetworkApplianceVpnSiteToSiteVpn(networkId)['subnets']
  File "/Users/phdonnelly/.pyenv/versions/3.8.1/lib/python3.8/site-packages/meraki/api/appliance.py", line 1338, in getNetworkApplianceVpnSiteToSiteVpn
    return self._session.get(metadata, resource)
  File "/Users/phdonnelly/.pyenv/versions/3.8.1/lib/python3.8/site-packages/meraki/rest_session.py", line 268, in get
    response = self.request(metadata, 'GET', url, params=params)
  File "/Users/phdonnelly/.pyenv/versions/3.8.1/lib/python3.8/site-packages/meraki/rest_session.py", line 256, in request
    raise APIError(metadata, response)
meraki.exceptions.APIError: appliance, getNetworkApplianceVpnSiteToSiteVpn - 400 Bad Request, {'errors': ['This endpoint only supports MX networks']}
Processing Porky Mobile Devices:  30%|██████████████████████████████████████████████████████████▏                                                                                                                                       | 30/100 [01:18<03:03,  2.62s/it]
```

I haven't looked into the API much/at all; maybe there's a capability or type field to filter against and exclude MDM stuff?

**Comment by phdonnelly** [comment]
Think I got a workaround/fix going:

In the get_sites function I added this snippet to exclude system manager networks.

Right after "    for network in networks:"

```
       if "systemsManager" in network["productTypes"]:
            print("Skipping unsupported System Manager Network")
            continue
```

Script is running now and has gotten further along than all the other attempts.

Only issue I see is if someone has a combined network with a supported device AND system manager. Maybe update the test to check the length of network["productTypes"] first.

**Comment by phdonnelly** [comment]
Better approach; I prevented some of the information gathering sections from trying to run at all if the appropriate product type was not present in the productTypes list (either switch or appliance). Diff attached

[checkProductTypesdiff.txt](https://github.com/picnicsecurity/Meraki-Traffic-Analyzer/files/5585856/checkProductTypesdiff.txt)

**Comment by JustOneMoreDog** [comment]
This is some excellent information thank you! I missed `network["productTypes"]` while building this and I like your implementation of it. If you open up a pull request I will happily get that merged in. I am going over the code now to double check it but I think what you did should work out just fine. I can test it on my end too.

**Comment by phdonnelly** [comment]
Awesome, sounds good; i'll send the PR in a few min.

**Comment by JustOneMoreDog** [comment]
https://github.com/picnicsecurity/Meraki-Traffic-Analyzer/pull/4
